docker:
  image: yegor256/rultor
assets:
  settings.xml: "portlek/secret-repo#general/settings.xml"
  pubring.gpg: "portlek/secret-repo#general/pubring.gpg"
  secring.gpg: "portlek/secret-repo#general/secring.gpg"
  "gradle.properties": "portlek/secret-repo#general/gradle.properties"
architect:
  - portlek
merge:
  script: |
    chmod +x gradlew
    ./gradlew -Dfile.encoding=utf-8 build
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    chmod +x gradlew
    ./gradlew -Dgradle.user.home="/home/r" -Dfile.encoding=utf-8 -PkekoutilVersion="${tag}" uploadArchives closeAndReleaseRepository