name: KekoUtil
main: tr.com.infumia.kekoutil.KekoUtilPlugin
version: '3.6'
author: infumia
api-version: '1.13'
softdepend:
  - Vault
  - PlaceholderAPI
  - LuckPerms
  - PermissionsEx
  - GroupManager
  - BentoBox
  - ASkyBlock
  - FabledSkyblock